mouse_support: true
max_watch_history: 50
allow_unicode: false
images: Sixels
refresh_after_modifying_search_filters: true
provider: YouTube
env:
  browser: xdg-open
  video-player: mpv
  youtube-downloader: yt-dlp
  terminal-emulator: kitty
